spring.application.name=PHLS-UK

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contact.phlsuk@gmail.com
spring.mail.password=tpwr mbni qegh gyfr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.address=0.0.0.0
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=never
server.error.include-stacktrace=never